### PR TITLE
Update harbour-olive-goes-shopping-pl.ts

### PR DESCRIPTION
**Pull request by atlochowski**

### CODE REVIEW

**Comment by PawelSpoon** [comment]
Hi !
i will merge without asking :)

you are also part of translation team in transifex.
why did you upload it into github ? did i miss a merge or should i promote you to reviewer ?

shall i update the transifex files too ?
let me know

**Comment by atlochowski** [comment]
Sorry, I don't know why I chose github. I was translating something in other project and I checked Olives... and  I  updated couple stings. 
Yes you shoul update transifex files.

**Comment by PawelSpoon** [comment]
hey !
that was my second colaboration on github :)

**Comment by PawelSpoon** [comment]
done

**Pull request merged**
