### PR TITLE
Update harbour-olive-goes-shopping-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Add slovak translate

### CODE REVIEW

**Review by PawelSpoon — APPROVED** [review]
hello, thank you for your contribution.
one has also to modify pro file i think to include a new language.
i will do that now
problem: i have currently not system to build the program
and i have not been able to setup obs chum
do you know that we have a transifex.com project for translations ?

**Comment by okruhliak** [comment]
do you know that we have a transifex.com project for translations ?

Hello, no, i did't know, can ju send me link, please?

**Comment by okruhliak** [comment]
Sorry, on https://openrepos.net/content/pawelspoon/olive-goes-shopping didn't find it, was I looking for it wrong?

**Comment by PawelSpoon** [comment]
seems the link got lost over the years.
sorry
https://www.transifex.com/pawelspoon/olive-goes-shopping/dashboard/


On Wednesday 24 November 2021 16:28:23 (+01:00), okruhliak wrote:



Sorry, on https://openrepos.net/content/pawelspoon/olive-goes-shopping didn't find it, was I looking for it wrong?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Pull request merged**
